
  transforms:
    LARM_chain_cb: [1, 1, 1, 1, 1, 1]
    RARM_chain_cb: [1, 1, 1, 1, 1, 1]
    # camera_ns
    hrp2_to_multisense: [0, 0, 0, 0, 0, 0]

  chains:
    LARM_chain:
      gearing: [0, 0, 0, 0, 0, 0, 0, 0]
    RARM_chain:
      gearing: [0, 0, 0, 0, 0, 0, 0, 0]
    head_chain:
      gearing: [0, 0]
    torso_chain:
      gearing: [0, 0]


  rectified_cams:
    head_camera:
      baseline_shift: 0
      f_shift: 0
      cx_shift: 0
      cy_shift: 0

  tilting_lasers: {}

  checkerboards:
    mmurooka_board:
      spacing_x: 0
      spacing_y: 0
