# hrp2jsknt_sim.yaml
# footstep successors
x:     [-0.039375,0.0525,0.0525,0.027176,-0.027176,-0.08,0.0,0.0,0.075,0.15,0.0, 0.15,  0.1, 0.0,  0.2,  0.25]
y:     [0.2475,0.26,0.26,0.206422,0.206422,0.21,0.27,0.19,0.21,0.21,0.21,        0.21, 0.21, 0.21, 0.21, 0.21]
theta: [0.174533,-0.20944,0.20944,-0.261799,0.261799,0.0,0.0,0.0,0.0,0.0,0.0,    0.0,  0.0,  0.0,  0.0,  0.0]

# coordinate system
lfoot_frame_id: LLEG_LINK5
rfoot_frame_id: RLEG_LINK5
# offset link coordinate -> center of foot
lfoot_offset: [0.052, 0.01, -0.105, 0, 0, 0, 1]
rfoot_offset: [0.052, -0.01, -0.105, 0, 0, 0, 1]
# offset link coordinate -> end coords
lfoot_endcoords_offset: [0.035589, 0.01, -0.105, 0, 0, 0, 1]
rfoot_endcoords_offset: [0.035589, -0.01, -0.105, 0, 0, 0, 1]
